export { renderSlots } from '../helpers/renderSlots'
export {h} from './h'
export {createTextVNode } from './vnode'
export {getCurrentInstance} from './component'
export {provide,inject} from './apiInject'
export {createRenderer} from './renderer'